### ISSUE TITLE
Importing Existing Resources

### ISSUE THREAD

**Issue by virendrasuryavanshi** [aws/aws-controllers-k8s#278] opened 2020-09-08 10:56 UTC
**Describe the solution you'd like**
To import the existing resources which are already provisioned in the AWS as Kubernetes CRDs.

**Describe alternatives you've considered**
https://crossplane.io/docs/v0.12/introduction/managed-resources.html

**Comment by mhausenblas** [comment] 2020-09-08 11:10
This is a dupe of #41

**Closed by mhausenblas** 2020-09-08 11:10 UTC
Labels: enhancement
