### ISSUE TITLE
mockery tests give errors

### ISSUE THREAD

**Issue by sebgoa** [aws/aws-controllers-k8s#326] opened 2020-09-23 08:43 UTC
On first run

```
$ make kind-test SERVICE=$SERVICE
/usr/local/bin/mockery --tags=codegen --case=underscore --output=mocks/pkg/compare --dir=pkg/compare --all
23 Sep 20 10:41 CEST INF Starting mockery dry-run=false version=2.2.1
23 Sep 20 10:41 CEST INF Walking dry-run=false version=2.2.1
/usr/local/bin/mockery --tags=codegen --case=underscore --output=mocks/pkg/errors --dir=pkg/errors --all
23 Sep 20 10:41 CEST INF Starting mockery dry-run=false version=2.2.1
23 Sep 20 10:41 CEST INF Walking dry-run=false version=2.2.1
/usr/local/bin/mockery --tags=codegen --case=underscore --output=mocks/pkg/generate --dir=pkg/generate --all
23 Sep 20 10:41 CEST INF Starting mockery dry-run=false version=2.2.1
23 Sep 20 10:41 CEST INF Walking dry-run=false version=2.2.1
23 Sep 20 10:41 CEST ERR Error parsing file error="/Users/sebgoa/go/src/github.com/sebgoa/aws-controllers-k8s/pkg/generate/config/config.go:215:60: Operation not declared by package api" dry-run=false version=2.2.1
23 Sep 20 10:41 CEST ERR Error parsing file error="/Users/sebgoa/go/src/github.com/sebgoa/aws-controllers-k8s/pkg/generate/generator.go:82:26: createOp.InputRef undefined (type *invalid type has no field or method InputRef)" dry-run=false version=2.2.1

```

**Comment by A-Hilaly** [comment] 2020-09-23 10:05
I can't reproduce your the errors @sebgoa , which version of mockery are you using?

**Comment by sebgoa** [comment] 2020-09-23 10:54
2.2.1

```
$ mockery --version
23 Sep 20 12:53 CEST INF Starting mockery dry-run=false version=2.2.1
2.2.1
```

On OSX 10.14.6

**Comment by smuralee** [comment] 2020-09-23 18:38
@A-Hilaly It's related to #265

**Comment by A-Hilaly** [comment] 2020-09-24 09:30
Thank you @smuralee . Let's close this a follow up the conversation in #265

**Closed by A-Hilaly** 2020-09-24 09:30 UTC
Labels: bug
