### ISSUE TITLE
Permissions issue in Elasticache controller

### ISSUE THREAD

**Issue by jaypipes** [aws/aws-controllers-k8s#367] opened 2020-10-02 18:53 UTC
Running the Elasticache e2e tests locally and I'm getting this:

```
ERROR	controller-runtime.controller	Reconciler error	{"controller": "cachesubnetgroup", "request": "default/ack-test-smoke-elasticache-subnet-gp", "error": "ServiceLinkedRoleNotFoundFault: This action cannot be completed due to insufficient permissions. (Recommended action) Please create new role using IAM API CreateServiceLinkedRole.\n\tstatus code: 400, request id: cbb0ea1c-30be-4a67-832c-efee32f1003f"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90
```

The policy I have associated with the IAM Role executing the service controller is:

```
arn:aws:iam::aws:policy/AmazonElastiCacheFullAccess
```

@kumargauravsharma is that not the correct policy?

**Comment by kumargauravsharma** [comment] 2020-10-14 14:25
I couldn't reproduce this issue.
I followed the steps mentioned for IAM Setup at https://github.com/aws/aws-controllers-k8s/blob/main/docs/contents/dev-docs/testing.md and 
and added `arn:aws:iam::aws:policy/AmazonElastiCacheFullAccess` policy to `$ACK_TEST_IAM_ROLE` and executed `SERVICE=elasticache make kind-test` and test ran without `ServiceLinkedRoleNotFoundFault` error.

I have added the run logs under PR: https://github.com/aws/aws-controllers-k8s/pull/411

Thus, `arn:aws:iam::aws:policy/AmazonElastiCacheFullAccess` seems correct policy.

**Comment by kumargauravsharma** [comment] 2020-10-23 00:28
Closing this issue as `arn:aws:iam::aws:policy/AmazonElastiCacheFullAccess` seems correct policy.

**Closed** 2020-10-23 00:28 UTC
Labels: Elasticache, bug
