### ISSUE TITLE
Error from server (NotFound): error when creating "STDIN": namespaces "testing" not found

### ISSUE THREAD

**Issue by saikrishnaa** [aws/aws-controllers-k8s#368] opened 2020-10-04 16:21 UTC
**issue:**  

Below issue occurred while configuring ACk for S3 service.
 
make kind-test SERVICE=$SERVICE

To poke around your test manually:
export KUBECONFIG=/home/ubuntu/aws-controllers-k8s/scripts/../build/tmp-test-944e9b8d/kubeconfig
kubectl get pods -A

Error from server (NotFound): error when creating "STDIN": namespaces "testing" not found
FAIL: expected ack-test-smoke-s3--11513 to have been created in S3
2020-10-04T15:30:09.164Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": "0.0.0.0:8080"}
2020-10-04T15:30:09.167Z	INFO	setup	initializing service controller	{"aws.service": "s3"}
2020-10-04T15:30:09.264Z	INFO	setup	starting manager	{"aws.service": "s3"}
2020-10-04T15:30:09.265Z	INFO	controller-runtime.controller	Starting EventSource	{"controller": "bucket", "source": "kind source: /, Kind="}
2020-10-04T15:30:09.265Z	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
E1004 15:30:09.267968       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:ack-system:default" cannot list resource "configmaps" in API group "" in the namespace "ack-system"
E1004 15:30:09.271967       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:ack-system:default" cannot list resource "namespaces" in API group "" at the cluster scope
2020-10-04T15:30:09.366Z	INFO	controller-runtime.controller	Starting Controller	{"controller": "bucket"}
2020-10-04T15:30:09.366Z	INFO	controller-runtime.controller	Starting workers	{"controller": "bucket", "worker count": 1}
E1004 15:30:10.605562       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:ack-system:default" cannot list resource "namespaces" in API group "" at the cluster scope
E1004 15:30:10.822993       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:ack-system:default" cannot list resource "configmaps" in API group "" in the namespace "ack-system"
E1004 15:30:12.889533       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:ack-system:default" cannot list resource "namespaces" in API group "" at the cluster scope
E1004 15:30:13.524275       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:ack-system:default" cannot list resource "configmaps" in API group "" in the namespace "ack-system"
E1004 15:30:16.302543       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:ack-system:default" cannot list resource "namespaces" in API group "" at the cluster scope
E1004 15:30:17.227922       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:ack-system:default" cannot list resource "configmaps" in API group "" in the namespace "ack-system"
E1004 15:30:23.325700       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:ack-system:default" cannot list resource "namespaces" in API group "" at the cluster scope
E1004 15:30:25.556133       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:ack-system:default" cannot list resource "configmaps" in API group "" in the namespace "ack-system"
E1004 15:30:42.723168       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:ack-system:default" cannot list resource "namespaces" in API group "" at the cluster scope
⏰ Took 489sec
❌ ACK Integration Test FAILED test-944e9b8d! ❌
To resume test with the same cluster use: "-c /home/ubuntu/aws-controllers-k8s/scripts/../build/tmp-test-944e9b8d"
Makefile:52: recipe for target 'kind-test' failed
make: *** [kind-test] Error 1

**Steps to reproduce**
make kind-test SERVICE=$SERVICE

Link for reference 👍 

https://aws.github.io/aws-controllers-k8s/dev-docs/testing/

**Expected outcome**

The Expected Output:

To poke around your test manually:
export KUBECONFIG=/Users/hausenbl/ACK/upstream/aws-controllers-k8s/scripts/../build/tmp-test-ccc3c7f1/kubeconfig
kubectl get pods -A

bucket.s3.services.k8s.aws/ack-test-smoke-s3 created
{
  "Name": "ack-test-smoke-s3",
  "CreationDate": "2020-08-18T08:52:04+00:00"
}
bucket.s3.services.k8s.aws "ack-test-smoke-s3" deleted
smoke took 27 second(s)
🥑 Deleting k8s cluster using "kind"
Deleting cluster "test-ccc3c7f1" ...

**Environment**
Operating System Ubuntu

* Kubernetes version
ubuntu@ack:~/aws-controllers-k8s$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-05-01T02:22:44Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

kind version
kind v0.9.0 go1.14.9 linux/amd64

* AWS service targeted (S3, RDS, etc.)
S3

**Comment by A-Hilaly** [comment] 2020-10-05 09:39
Hi @saikrishnaa , thank you for the report. This has been mentionned in https://github.com/aws/aws-controllers-k8s/pull/354#discussion_r498401505 . I'm sending a fix today.

**Comment by saikrishnaa** [comment] 2020-10-05 09:45
Hello @A-Hilaly, Thanks for Update.

**Comment by A-Hilaly** [comment] 2020-10-13 10:39
We just merged the fix yesterday @saikrishnaa :). Can you please give it a try, and provide feedback if possible?

**Comment by saikrishnaa** [comment] 2020-10-15 17:00
Hello @A-Hilaly 

I tried reconfiguring but im getting stuck near. Any idea on this ??? 

**Error** 
ubuntu@test: ~/aws-controllers-k8s$  make build-ack-generate
building ack-generate ... ok.
ubuntu@test: ~/aws-controllers-k8s$  make build-controller SERVICE=$SERVICE
building ack-generate ... ok.
FATAL: Missing requirement 'controller-gen'
Please install controller-gen before running this script.

You can install controller-gen with the helper scripts/install-controller-gen.sh

Makefile:50: recipe for target 'build-controller' failed
make: *** [buid-controller] Error 1

**I tried with this:**

ubuntu@test: ~/aws-controllers-k8s$ sudo ./scripts/install-controller-gen.sh
installing controller-gen v0.4.0 ... mv: cannot stat '/tmp/controller-gen-Zun/controller-gen': No such file or directory
ok.
ubuntu@test: ~/aws-controllers-k8s$

**Comment by A-Hilaly** [comment] 2020-10-15 17:57
Hi @saikrishnaa 
I am not able to reproduce your error. Can you please inspect the content of your `/tmp/controller-gen-Zun` directory ?

**Comment by jaypipes** [comment] 2020-10-16 16:15
Closing this issue out, as the original issue has been fixed. @saikrishnaa if there is a separate problem with the controller-gen installation, would you mind creating a separate GH issue for that? Thank you!

**Closed by jaypipes** 2020-10-16 16:15 UTC
Labels: bug
